//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Расписание()
        {
            this.Успеваемость = new HashSet<Успеваемость>();
        }
    
        public int ID { get; set; }
        public string Кабинет { get; set; }
        public string День_недели { get; set; }
        public System.DateTime Дата { get; set; }
        public int ID_пары { get; set; }
        public int Порядковый_номер_пары { get; set; }
        public int ID_Группы { get; set; }
    
        public virtual Группы Группы { get; set; }
        public virtual Дисциплины Дисциплины { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Успеваемость> Успеваемость { get; set; }
    }
}
