//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Успеваемость
    {
        public int ID { get; set; }
        public int ID_студента { get; set; }
        public int ID_преподавателя { get; set; }
        public int ID_предмета { get; set; }
        public string оценка { get; set; }
    
        public virtual Преподаватели Преподаватели { get; set; }
        public virtual Расписание Расписание { get; set; }
        public virtual Студенты Студенты { get; set; }
    }
}
